require("dotenv").config();

// console.log("Environment Variables:", process.env);

const {
  CUSTOMERSERVICE_DBHOST,
  CUSTOMERSERVICE_DBUSER,
  CUSTOMERSERVICE_DBPASS,
  CUSTOMERSERVICE_DBNAME,
  CUSTOMERSERVICE_DBPORT,
} = process.env;

module.exports = {
  DB_HOST: CUSTOMERSERVICE_DBHOST,
  DB_USER: CUSTOMERSERVICE_DBUSER,
  DB_PASSWORD: CUSTOMERSERVICE_DBPASS,
  DB_NAME: CUSTOMERSERVICE_DBNAME,
  DB_PORT: CUSTOMERSERVICE_DBPORT,
};
